import {
    Transaction,
    MonthlyData,
    CategoryData,
    IncomeSource,
    Budget,
    ReportSummary,
} from "@/types";

// ── Dashboard ────────────────────────────────────────────────────────

export const monthlyData: MonthlyData[] = [
    { month: "Jan", income: 4200, expenses: 2800 },
    { month: "Feb", income: 4500, expenses: 3100 },
    { month: "Mar", income: 4100, expenses: 2600 },
    { month: "Apr", income: 4800, expenses: 3400 },
    { month: "May", income: 5200, expenses: 3000 },
    { month: "Jun", income: 4900, expenses: 3200 },
    { month: "Jul", income: 5100, expenses: 2900 },
    { month: "Aug", income: 5400, expenses: 3500 },
    { month: "Sep", income: 4700, expenses: 3100 },
    { month: "Oct", income: 5000, expenses: 3300 },
    { month: "Nov", income: 5300, expenses: 3600 },
    { month: "Dec", income: 5600, expenses: 3800 },
];

export const categoryData: CategoryData[] = [
    { name: "Food", value: 1250, color: "#f97316" },
    { name: "Transport", value: 850, color: "#3b82f6" },
    { name: "Shopping", value: 1100, color: "#a855f7" },
    { name: "Bills", value: 1400, color: "#ef4444" },
    { name: "Entertainment", value: 650, color: "#22c55e" },
];

export const transactions: Transaction[] = [
    {
        id: "1",
        date: "2026-04-20",
        description: "Grocery Store",
        category: "Food",
        amount: -85.5,
        status: "completed",
        type: "expense",
    },
    {
        id: "2",
        date: "2026-04-19",
        description: "Monthly Salary",
        category: "Income",
        amount: 5200.0,
        status: "completed",
        type: "income",
    },
    {
        id: "3",
        date: "2026-04-18",
        description: "Electric Bill",
        category: "Bills",
        amount: -142.3,
        status: "completed",
        type: "expense",
    },
    {
        id: "4",
        date: "2026-04-17",
        description: "Uber Ride",
        category: "Transport",
        amount: -24.5,
        status: "completed",
        type: "expense",
    },
    {
        id: "5",
        date: "2026-04-16",
        description: "Netflix Subscription",
        category: "Entertainment",
        amount: -15.99,
        status: "completed",
        type: "expense",
    },
    {
        id: "6",
        date: "2026-04-15",
        description: "Freelance Payment",
        category: "Income",
        amount: 1200.0,
        status: "pending",
        type: "income",
    },
    {
        id: "7",
        date: "2026-04-14",
        description: "Amazon Purchase",
        category: "Shopping",
        amount: -67.8,
        status: "completed",
        type: "expense",
    },
    {
        id: "8",
        date: "2026-04-13",
        description: "Restaurant Dinner",
        category: "Food",
        amount: -52.4,
        status: "completed",
        type: "expense",
    },
    {
        id: "9",
        date: "2026-04-12",
        description: "Gas Station",
        category: "Transport",
        amount: -45.0,
        status: "failed",
        type: "expense",
    },
    {
        id: "10",
        date: "2026-04-11",
        description: "Water Bill",
        category: "Bills",
        amount: -38.9,
        status: "completed",
        type: "expense",
    },
];

export const summaryData = {
    totalBalance: 12_540.8,
    totalIncome: 58_800.0,
    totalExpenses: 38_400.0,
    savings: 20_400.0,
    balanceChange: 12.5,
    incomeChange: 8.2,
    expenseChange: -3.1,
    savingsChange: 15.3,
};

// ── Expenses page ────────────────────────────────────────────────────

export const allExpenses: Transaction[] = [
    ...transactions.filter((t) => t.type === "expense"),
    {
        id: "11",
        date: "2026-04-10",
        description: "Gym Membership",
        category: "Health",
        amount: -49.99,
        status: "completed",
        type: "expense",
    },
    {
        id: "12",
        date: "2026-04-09",
        description: "Coffee Shop",
        category: "Food",
        amount: -12.5,
        status: "completed",
        type: "expense",
    },
    {
        id: "13",
        date: "2026-04-08",
        description: "Phone Bill",
        category: "Bills",
        amount: -65.0,
        status: "completed",
        type: "expense",
    },
    {
        id: "14",
        date: "2026-04-07",
        description: "Movie Tickets",
        category: "Entertainment",
        amount: -28.0,
        status: "completed",
        type: "expense",
    },
    {
        id: "15",
        date: "2026-04-06",
        description: "Clothing Store",
        category: "Shopping",
        amount: -134.5,
        status: "completed",
        type: "expense",
    },
    {
        id: "16",
        date: "2026-04-05",
        description: "Internet Bill",
        category: "Bills",
        amount: -79.99,
        status: "pending",
        type: "expense",
    },
    {
        id: "17",
        date: "2026-04-04",
        description: "Parking Fee",
        category: "Transport",
        amount: -15.0,
        status: "completed",
        type: "expense",
    },
    {
        id: "18",
        date: "2026-04-03",
        description: "Spotify Premium",
        category: "Entertainment",
        amount: -9.99,
        status: "completed",
        type: "expense",
    },
];

// ── Income page ──────────────────────────────────────────────────────

export const incomeSources: IncomeSource[] = [
    {
        id: "i1",
        source: "Monthly Salary",
        category: "Employment",
        amount: 5200,
        date: "2026-04-19",
        recurring: true,
        status: "received",
    },
    {
        id: "i2",
        source: "Freelance Web Project",
        category: "Freelance",
        amount: 1200,
        date: "2026-04-15",
        recurring: false,
        status: "pending",
    },
    {
        id: "i3",
        source: "Stock Dividends",
        category: "Investments",
        amount: 340,
        date: "2026-04-10",
        recurring: true,
        status: "received",
    },
    {
        id: "i4",
        source: "Rental Income",
        category: "Real Estate",
        amount: 1800,
        date: "2026-04-01",
        recurring: true,
        status: "received",
    },
    {
        id: "i5",
        source: "YouTube Ad Revenue",
        category: "Side Hustle",
        amount: 420,
        date: "2026-03-28",
        recurring: true,
        status: "received",
    },
    {
        id: "i6",
        source: "Consulting Fee",
        category: "Freelance",
        amount: 950,
        date: "2026-03-22",
        recurring: false,
        status: "received",
    },
    {
        id: "i7",
        source: "Tax Refund",
        category: "Government",
        amount: 2100,
        date: "2026-03-15",
        recurring: false,
        status: "received",
    },
    {
        id: "i8",
        source: "Bonus",
        category: "Employment",
        amount: 3000,
        date: "2026-03-01",
        recurring: false,
        status: "overdue",
    },
];

export const incomeByCategory: CategoryData[] = [
    { name: "Employment", value: 8200, color: "#22c55e" },
    { name: "Freelance", value: 2150, color: "#3b82f6" },
    { name: "Investments", value: 340, color: "#a855f7" },
    { name: "Real Estate", value: 1800, color: "#f97316" },
    { name: "Side Hustle", value: 420, color: "#06b6d4" },
    { name: "Government", value: 2100, color: "#64748b" },
];

// ── Budgets page ─────────────────────────────────────────────────────

export const budgets: Budget[] = [
    { id: "b1", category: "Food", budgeted: 1500, spent: 1250, color: "#f97316" },
    {
        id: "b2",
        category: "Transport",
        budgeted: 1000,
        spent: 850,
        color: "#3b82f6",
    },
    {
        id: "b3",
        category: "Shopping",
        budgeted: 800,
        spent: 1100,
        color: "#a855f7",
    },
    { id: "b4", category: "Bills", budgeted: 1600, spent: 1400, color: "#ef4444" },
    {
        id: "b5",
        category: "Entertainment",
        budgeted: 500,
        spent: 650,
        color: "#22c55e",
    },
    { id: "b6", category: "Health", budgeted: 300, spent: 180, color: "#06b6d4" },
    {
        id: "b7",
        category: "Education",
        budgeted: 400,
        spent: 250,
        color: "#eab308",
    },
    { id: "b8", category: "Savings", budgeted: 2000, spent: 1800, color: "#14b8a6" },
];

// ── Reports page ─────────────────────────────────────────────────────

export const reportSummary: ReportSummary[] = [
    {
        month: "Jan",
        income: 4200,
        expenses: 2800,
        savings: 1400,
        savingsRate: 33.3,
    },
    {
        month: "Feb",
        income: 4500,
        expenses: 3100,
        savings: 1400,
        savingsRate: 31.1,
    },
    {
        month: "Mar",
        income: 4100,
        expenses: 2600,
        savings: 1500,
        savingsRate: 36.6,
    },
    {
        month: "Apr",
        income: 4800,
        expenses: 3400,
        savings: 1400,
        savingsRate: 29.2,
    },
    {
        month: "May",
        income: 5200,
        expenses: 3000,
        savings: 2200,
        savingsRate: 42.3,
    },
    {
        month: "Jun",
        income: 4900,
        expenses: 3200,
        savings: 1700,
        savingsRate: 34.7,
    },
    {
        month: "Jul",
        income: 5100,
        expenses: 2900,
        savings: 2200,
        savingsRate: 43.1,
    },
    {
        month: "Aug",
        income: 5400,
        expenses: 3500,
        savings: 1900,
        savingsRate: 35.2,
    },
    {
        month: "Sep",
        income: 4700,
        expenses: 3100,
        savings: 1600,
        savingsRate: 34.0,
    },
    {
        month: "Oct",
        income: 5000,
        expenses: 3300,
        savings: 1700,
        savingsRate: 34.0,
    },
    {
        month: "Nov",
        income: 5300,
        expenses: 3600,
        savings: 1700,
        savingsRate: 32.1,
    },
    {
        month: "Dec",
        income: 5600,
        expenses: 3800,
        savings: 1800,
        savingsRate: 32.1,
    },
];

export const topExpenseCategories: CategoryData[] = [
    { name: "Bills", value: 18200, color: "#ef4444" },
    { name: "Food", value: 15600, color: "#f97316" },
    { name: "Shopping", value: 12400, color: "#a855f7" },
    { name: "Transport", value: 9800, color: "#3b82f6" },
    { name: "Entertainment", value: 7200, color: "#22c55e" },
];
